[package]
edition = "2021"
name = "c_kornei_korneevich_ixorprostaya_versiya"
version = "0.1.0"

[dependencies]
algo_lib = {path = "../algo_lib"}
rand = "0.8.5"

[build-dependencies]
rust_competitive_helper_util = {git = "https://github.com/rust-competitive-helper/rust-competitive-helper"}
